import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedKUDIDWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedRectangle52Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedFrame4Widget4.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedBUYWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedUNITNAMEWidget3.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedLine3Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedLine6Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedLine5Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedLine1Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedFrame3Widget3.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedQUANTITYWidget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedRectangle51Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedLine4Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedRectangle20Widget3.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax13widget/generated/GeneratedLine2Widget1.dart';

/* Frame iPhone 11 Pro Max - 13
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax13Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 918.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 918.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 225, 232, 235),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 455.0,
                              height: 83.0,
                              child: GeneratedFrame3Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 835.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 83.0,
                              child: GeneratedFrame4Widget4(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 361.0,
                              height: 39.0,
                              child: GeneratedRectangle20Widget3(),
                            ),
                            Positioned(
                              left: 22.760501861572266,
                              top: 243.81651306152344,
                              right: null,
                              bottom: null,
                              width: 373.0,
                              height: 569.0,
                              child: GeneratedRectangle51Widget2(),
                            ),
                            Positioned(
                              left: 298.0,
                              top: 314.0,
                              right: null,
                              bottom: null,
                              width: 84.0,
                              height: 39.0,
                              child: GeneratedRectangle52Widget(),
                            ),
                            Positioned(
                              left: 319.0,
                              top: 323.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 28.0,
                              child: GeneratedBUYWidget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 242.0,
                              right: null,
                              bottom: null,
                              width: 570.0078735351562,
                              height: 1.0,
                              child: GeneratedLine1Widget1(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 242.0,
                              right: null,
                              bottom: null,
                              width: 570.0078735351562,
                              height: 1.0,
                              child: GeneratedLine8Widget(),
                            ),
                            Positioned(
                              left: 284.0,
                              top: 240.0,
                              right: null,
                              bottom: null,
                              width: 570.0078735351562,
                              height: 1.0,
                              child: GeneratedLine7Widget(),
                            ),
                            Positioned(
                              left: 397.0,
                              top: 242.0,
                              right: null,
                              bottom: null,
                              width: 570.0078735351562,
                              height: 1.0,
                              child: GeneratedLine5Widget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 242.0,
                              right: null,
                              bottom: null,
                              width: 570.0078735351562,
                              height: 1.0,
                              child: GeneratedLine4Widget1(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 378.0052795410156,
                              height: 1.0,
                              child: GeneratedLine2Widget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 810.0,
                              right: null,
                              bottom: null,
                              width: 378.0052795410156,
                              height: 1.0,
                              child: GeneratedLine6Widget1(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 242.0,
                              right: null,
                              bottom: null,
                              width: 378.0052795410156,
                              height: 1.0,
                              child: GeneratedLine3Widget1(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 255.0,
                              right: null,
                              bottom: null,
                              width: 69.0,
                              height: 25.0,
                              child: GeneratedKUDIDWidget(),
                            ),
                            Positioned(
                              left: 172.0,
                              top: 259.0,
                              right: null,
                              bottom: null,
                              width: 105.0,
                              height: 28.0,
                              child: GeneratedQUANTITYWidget1(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 151.0,
                              right: null,
                              bottom: null,
                              width: 139.0,
                              height: 31.0,
                              child: GeneratedUNITNAMEWidget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
