import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax3widget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax3widget/generated/GeneratedVectorWidget3.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax3widget/generated/GeneratedSuccesfullyRegistredWidget.dart';

/* Frame iPhone 11 Pro Max - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedLoadingscreenWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 225, 232, 235),
                  ),
                ),
                Positioned(
                  left: 108.0,
                  top: 277.0,
                  right: null,
                  bottom: null,
                  width: 198.0,
                  height: 189.0,
                  child: GeneratedEllipse1Widget(),
                ),
                Positioned(
                  left: 126.0,
                  top: 294.0,
                  right: null,
                  bottom: null,
                  width: 162.0,
                  height: 154.0,
                  child: GeneratedVectorWidget3(),
                ),
                Positioned(
                  left: 44.0,
                  top: 492.0,
                  right: null,
                  bottom: null,
                  width: 372.0,
                  height: 45.0,
                  child: GeneratedSuccesfullyRegistredWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
