import 'package:flutter/material.dart';

/* Component Text
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTextWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 0.0,
      height: 40.0,
    ));
  }
}
