import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloginorregisterwidget/generated/GeneratedContinueaskudumbasreeWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloginorregisterwidget/generated/GeneratedContinueascompanyWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloginorregisterwidget/generated/GeneratedREGISTERWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloginorregisterwidget/generated/GeneratedOrWidget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloginorregisterwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloginorregisterwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloginorregisterwidget/generated/GeneratedOrWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloginorregisterwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloginorregisterwidget/generated/GeneratedLOGINWidget2.dart';

/* Frame login or register
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginorregisterWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(100.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(100.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(100.0),
                child: Container(
                  color: Color.fromARGB(255, 40, 39, 118),
                ),
              ),
              Positioned(
                left: 112.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 1.0,
                height: 6.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 64.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 64.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 45.0,
                child: GeneratedREGISTERWidget(),
              ),
              Positioned(
                left: 141.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 45.0,
                child: GeneratedLOGINWidget2(),
              ),
              Positioned(
                left: 182.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 34.0,
                child: GeneratedOrWidget(),
              ),
              Positioned(
                left: 182.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 189.0,
                child: GeneratedOrWidget1(),
              ),
              Positioned(
                left: 53.0,
                top: 435.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 31.0,
                child: GeneratedContinueaskudumbasreeWidget(),
              ),
              Positioned(
                left: 68.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 31.0,
                child: GeneratedContinueascompanyWidget(),
              )
            ]),
      ),
    ));
  }
}
