import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedframe4widget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedframe4widget/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedframe4widget/generated/GeneratedSUBMITWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedframe4widget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedframe4widget/generated/GeneratedTellustheaddressfromwherewewillpickuptheitemsWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedframe4widget/generated/GeneratedSearchlocationWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedframe4widget/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedframe4widget/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedframe4widget/generated/GeneratedVectorWidget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedframe4widget/generated/GeneratedSelectthelocationwhereyouwoulddroptheitemWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedframe4widget/generated/GeneratedRectangle29Widget.dart';

/* Frame Frame 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 225, 232, 235),
                ),
              ),
              Positioned(
                left: 28.0,
                top: 347.0,
                right: null,
                bottom: null,
                width: 29.656158447265625,
                height: 21.774017333984375,
                child: GeneratedVectorWidget1(),
              ),
              Positioned(
                left: 64.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 47.0,
                child:
                    GeneratedTellustheaddressfromwherewewillpickuptheitemsWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 29.656173706054688,
                height: 27.217514038085938,
                child: GeneratedSearchlocationWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 83.0,
                child: GeneratedFrame5Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 801.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedFrame6Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedRectangle31Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 473.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedRectangle30Widget(),
              ),
              Positioned(
                left: 68.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 53.0,
                child:
                    GeneratedSelectthelocationwhereyouwoulddroptheitemWidget(),
              ),
              Positioned(
                left: 105.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 58.0,
                child: GeneratedRectangle25Widget(),
              ),
              Positioned(
                left: 158.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 26.0,
                child: GeneratedSUBMITWidget(),
              )
            ]),
      ),
    ));
  }
}
