import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedRectangle16Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedRectangle18Widget4.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedPASSWORDWidget3.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedRectangle15Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedFrame1Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedEMAILIDWidget3.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedCONFIRMPASSWORDWidget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedLOCATIONWidget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedCOMPANYNAMEWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedRectangle14Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedRectangle17Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedMANAGERNAMEWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedRectangle19Widget4.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration2widget/generated/GeneratedOKWidget2.dart';

/* Frame Registration2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistration2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 225, 232, 235),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 31.0,
                child: GeneratedCOMPANYNAMEWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 34.0,
                child: GeneratedPASSWORDWidget3(),
              ),
              Positioned(
                left: 35.0,
                top: 713.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 31.0,
                child: GeneratedCONFIRMPASSWORDWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 31.0,
                child: GeneratedMANAGERNAMEWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 34.0,
                child: GeneratedLOCATIONWidget2(),
              ),
              Positioned(
                left: 43.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 31.0,
                child: GeneratedEMAILIDWidget3(),
              ),
              Positioned(
                left: 16.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle14Widget2(),
              ),
              Positioned(
                left: 29.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle15Widget2(),
              ),
              Positioned(
                left: 35.0,
                top: 643.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle18Widget4(),
              ),
              Positioned(
                left: 16.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle17Widget2(),
              ),
              Positioned(
                left: 22.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle19Widget4(),
              ),
              Positioned(
                left: 24.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 96.0,
                child: GeneratedRectangle16Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 83.0,
                child: GeneratedFrame1Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 83.0,
                child: GeneratedFrame2Widget(),
              ),
              Positioned(
                left: 144.0,
                top: 830.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 37.0,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 180.0,
                top: 838.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 26.0,
                child: GeneratedOKWidget2(),
              )
            ]),
      ),
    ));
  }
}
