import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax5widget/generated/GeneratedRectangle20Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax5widget/generated/GeneratedPINCODEWidget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax5widget/generated/GeneratedPLACEWidget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax5widget/generated/GeneratedUNITNAMEWidget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax5widget/generated/GeneratedFrame3Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax5widget/generated/GeneratedRectangle23Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax5widget/generated/GeneratedSEARCHWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax5widget/generated/GeneratedRectangle22Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax5widget/generated/GeneratedFrame4Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax5widget/generated/GeneratedRectangle24Widget1.dart';

/* Frame iPhone 11 Pro Max - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 918.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 918.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 225, 232, 235),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 455.0,
                              height: 83.0,
                              child: GeneratedFrame3Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 835.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 83.0,
                              child: GeneratedFrame4Widget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 361.0,
                              height: 39.0,
                              child: GeneratedRectangle20Widget1(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 312.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 58.0,
                              child: GeneratedRectangle22Widget1(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 459.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 58.0,
                              child: GeneratedRectangle23Widget1(),
                            ),
                            Positioned(
                              left: 104.0,
                              top: 583.0,
                              right: null,
                              bottom: null,
                              width: 175.0,
                              height: 58.0,
                              child: GeneratedRectangle24Widget1(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 259.0,
                              right: null,
                              bottom: null,
                              width: 74.0,
                              height: 58.0,
                              child: GeneratedPLACEWidget2(),
                            ),
                            Positioned(
                              left: 152.0,
                              top: 601.0,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 28.0,
                              child: GeneratedSEARCHWidget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 406.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 28.0,
                              child: GeneratedPINCODEWidget1(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 155.0,
                              right: null,
                              bottom: null,
                              width: 139.0,
                              height: 31.0,
                              child: GeneratedUNITNAMEWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
