import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget/generated/GeneratedNAPYCOLLECTWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget/generated/GeneratedVectorWidget.dart';

/* Frame Loading screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoadingscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedLoginorregisterWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 40, 39, 118),
                  ),
                ),
                Positioned(
                  left: 92.0,
                  top: 487.0,
                  right: null,
                  bottom: null,
                  width: 246.0,
                  height: 44.0,
                  child: GeneratedNAPYCOLLECTWidget(),
                ),
                Positioned(
                  left: 161.0,
                  top: 356.0,
                  right: null,
                  bottom: null,
                  width: 106.0,
                  height: 68.0,
                  child: GeneratedVectorWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
