import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedPASSWORDWidget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedUNITNOWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedRectangle25Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedEMAILIDWidget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedLOCATIONWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedUNITNAMEWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedOKWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedCONFIRMPASSWORDWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration1widget/generated/GeneratedRectangle17Widget.dart';

/* Frame Registration1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistration1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 225, 232, 235),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 31.0,
                child: GeneratedUNITNAMEWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 593.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 34.0,
                child: GeneratedPASSWORDWidget1(),
              ),
              Positioned(
                left: 35.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 31.0,
                child: GeneratedCONFIRMPASSWORDWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 31.0,
                child: GeneratedUNITNOWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 34.0,
                child: GeneratedLOCATIONWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 31.0,
                child: GeneratedEMAILIDWidget1(),
              ),
              Positioned(
                left: 35.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 96.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 83.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 157.0,
                top: 827.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 37.0,
                child: GeneratedRectangle25Widget1(),
              ),
              Positioned(
                left: 194.0,
                top: 835.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 26.0,
                child: GeneratedOKWidget(),
              )
            ]),
      ),
    ));
  }
}
