import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedITEM_8Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle32Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedITEM_1Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle49Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle24Widget3.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedITEM_2Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle34Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle40Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle45Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle42Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedITEM_4Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle44Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle23Widget3.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle25Widget4.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle47Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedITEM_6Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedFrame4Widget6.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle43Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle37Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle48Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedFrame3Widget5.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedITEM_3Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle33Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedITEM_5Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle38Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle39Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle36Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedITEM_9Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedSEARCHWidget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle46Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedITEM_7Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedPINCODEWidget3.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax10widget/generated/GeneratedRectangle41Widget1.dart';

/* Frame iPhone 11 Pro Max - 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 918.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 918.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 225, 232, 235),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 455.0,
                              height: 83.0,
                              child: GeneratedFrame3Widget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 835.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 83.0,
                              child: GeneratedFrame4Widget6(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 612.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 37.0,
                              child: GeneratedRectangle23Widget3(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 713.0,
                              right: null,
                              bottom: null,
                              width: 175.0,
                              height: 58.0,
                              child: GeneratedRectangle24Widget3(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 136.0,
                              right: null,
                              bottom: null,
                              width: 74.0,
                              height: 58.0,
                              child: GeneratedITEM_1Widget1(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 181.0,
                              right: null,
                              bottom: null,
                              width: 107.0,
                              height: 58.0,
                              child: GeneratedITEM_2Widget1(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 230.0,
                              right: null,
                              bottom: null,
                              width: 139.0,
                              height: 58.0,
                              child: GeneratedITEM_3Widget1(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 279.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 58.0,
                              child: GeneratedITEM_4Widget1(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 333.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 58.0,
                              child: GeneratedITEM_5Widget1(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 386.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 58.0,
                              child: GeneratedITEM_6Widget1(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 439.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 58.0,
                              child: GeneratedITEM_7Widget1(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 489.0,
                              right: null,
                              bottom: null,
                              width: 95.0,
                              height: 58.0,
                              child: GeneratedITEM_8Widget1(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 539.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 58.0,
                              child: GeneratedITEM_9Widget1(),
                            ),
                            Positioned(
                              left: 158.0,
                              top: 731.0,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 28.0,
                              child: GeneratedSEARCHWidget1(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 616.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 28.0,
                              child: GeneratedPINCODEWidget3(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 154.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle32Widget1(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 200.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle33Widget1(),
                            ),
                            Positioned(
                              left: 222.0,
                              top: 298.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle34Widget1(),
                            ),
                            Positioned(
                              left: 221.0,
                              top: 351.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle37Widget1(),
                            ),
                            Positioned(
                              left: 222.0,
                              top: 408.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle38Widget1(),
                            ),
                            Positioned(
                              left: 222.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle39Widget1(),
                            ),
                            Positioned(
                              left: 222.0,
                              top: 510.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle40Widget1(),
                            ),
                            Positioned(
                              left: 221.0,
                              top: 556.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle41Widget1(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 249.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle36Widget1(),
                            ),
                            Positioned(
                              left: 281.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle25Widget4(),
                            ),
                            Positioned(
                              left: 281.0,
                              top: 214.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle42Widget1(),
                            ),
                            Positioned(
                              left: 282.0,
                              top: 265.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle43Widget1(),
                            ),
                            Positioned(
                              left: 281.0,
                              top: 313.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle44Widget1(),
                            ),
                            Positioned(
                              left: 282.0,
                              top: 367.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle45Widget1(),
                            ),
                            Positioned(
                              left: 281.0,
                              top: 423.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle46Widget1(),
                            ),
                            Positioned(
                              left: 282.0,
                              top: 469.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle47Widget1(),
                            ),
                            Positioned(
                              left: 276.0,
                              top: 525.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle48Widget1(),
                            ),
                            Positioned(
                              left: 276.0,
                              top: 571.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle49Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
