import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedLOCATIONWidget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedOKWidget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedFrame1Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedPHONENOWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedNAMEWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedCONFIRMPASSWORDWidget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedEMAILIDWidget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedPASSWORDWidget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedRectangle19Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedRectangle18Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedregistration3widget/generated/GeneratedRectangle15Widget1.dart';

/* Frame Registration3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistration3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 225, 232, 235),
                ),
              ),
              Positioned(
                left: 17.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 31.0,
                child: GeneratedNAMEWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 611.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 34.0,
                child: GeneratedPASSWORDWidget2(),
              ),
              Positioned(
                left: 35.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 31.0,
                child: GeneratedCONFIRMPASSWORDWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 31.0,
                child: GeneratedPHONENOWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 34.0,
                child: GeneratedLOCATIONWidget1(),
              ),
              Positioned(
                left: 35.0,
                top: 494.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 31.0,
                child: GeneratedEMAILIDWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 147.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle14Widget1(),
              ),
              Positioned(
                left: 29.0,
                top: 541.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle15Widget1(),
              ),
              Positioned(
                left: 35.0,
                top: 658.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle18Widget2(),
              ),
              Positioned(
                left: 23.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle17Widget1(),
              ),
              Positioned(
                left: 35.0,
                top: 775.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedRectangle19Widget2(),
              ),
              Positioned(
                left: 24.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 96.0,
                child: GeneratedRectangle16Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 83.0,
                child: GeneratedFrame1Widget1(),
              ),
              Positioned(
                left: 152.0,
                top: 844.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 37.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 189.0,
                top: 852.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 26.0,
                child: GeneratedOKWidget1(),
              )
            ]),
      ),
    ));
  }
}
