import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget1/generated/GeneratedForgotpasswordWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget1/generated/GeneratedEMAILIDWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget1/generated/GeneratedPASSWORDWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget1/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget1/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget1/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget1/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget1/generated/GeneratedLOGINWidget1.dart';

/* Frame Loading screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoadingscreenWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 40, 39, 118),
                ),
              ),
              Positioned(
                left: 155.0,
                top: 209.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 45.0,
                child: GeneratedLOGINWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 64.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 402.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 64.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 145.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 28.0,
                child: GeneratedPASSWORDWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 64.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 205.0,
                height: 31.0,
                child: GeneratedForgotpasswordWidget(),
              ),
              Positioned(
                left: 155.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 25.0,
                child: GeneratedEMAILIDWidget(),
              ),
              Positioned(
                left: 148.0,
                top: 516.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 45.0,
                child: GeneratedLOGINWidget1(),
              )
            ]),
      ),
    ));
  }
}
