import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax11widget/generated/GeneratedFrame3Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax11widget/generated/GeneratedUNITNAMEWidget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax11widget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax11widget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax11widget/generated/GeneratedRectangle20Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax11widget/generated/GeneratedRectangle51Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax11widget/generated/GeneratedLOCATIONWidget4.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax11widget/generated/GeneratedQUANTITYWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax11widget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax11widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax11widget/generated/GeneratedFrame4Widget3.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax11widget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax11widget/generated/GeneratedLine4Widget.dart';

/* Frame iPhone 11 Pro Max - 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 918.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 918.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 225, 232, 235),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 455.0,
                              height: 83.0,
                              child: GeneratedFrame3Widget2(),
                            ),
                            Positioned(
                              left: 4.0,
                              top: 811.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 83.0,
                              child: GeneratedFrame4Widget3(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 141.0,
                              right: null,
                              bottom: null,
                              width: 361.0,
                              height: 39.0,
                              child: GeneratedRectangle20Widget2(),
                            ),
                            Positioned(
                              left: 22.760501861572266,
                              top: 243.81651306152344,
                              right: null,
                              bottom: null,
                              width: 373.0,
                              height: 569.0,
                              child: GeneratedRectangle51Widget1(),
                            ),
                            Positioned(
                              left: 207.0,
                              top: 242.0,
                              right: null,
                              bottom: null,
                              width: 570.0078735351562,
                              height: 1.0,
                              child: GeneratedLine1Widget(),
                            ),
                            Positioned(
                              left: 397.0,
                              top: 242.0,
                              right: null,
                              bottom: null,
                              width: 570.0078735351562,
                              height: 1.0,
                              child: GeneratedLine5Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 242.0,
                              right: null,
                              bottom: null,
                              width: 570.0078735351562,
                              height: 1.0,
                              child: GeneratedLine4Widget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 378.0052795410156,
                              height: 1.0,
                              child: GeneratedLine2Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 810.0,
                              right: null,
                              bottom: null,
                              width: 378.0052795410156,
                              height: 1.0,
                              child: GeneratedLine6Widget(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 242.0,
                              right: null,
                              bottom: null,
                              width: 378.0052795410156,
                              height: 1.0,
                              child: GeneratedLine3Widget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 255.0,
                              right: null,
                              bottom: null,
                              width: 104.0,
                              height: 28.0,
                              child: GeneratedLOCATIONWidget4(),
                            ),
                            Positioned(
                              left: 229.0,
                              top: 259.0,
                              right: null,
                              bottom: null,
                              width: 105.0,
                              height: 28.0,
                              child: GeneratedQUANTITYWidget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 151.0,
                              right: null,
                              bottom: null,
                              width: 139.0,
                              height: 31.0,
                              child: GeneratedUNITNAMEWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
