import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle46Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedITEM_2Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle44Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedLOCATIONWidget5.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedITEM_6Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle25Widget3.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedFrame3Widget4.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle42Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle39Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle49Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle36Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle37Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle40Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedPINCODEWidget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedITEM_8Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedITEM_1Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle50Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle20Widget4.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedITEM_5Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedITEM_9Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedITEM_3Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle24Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedFrame4Widget5.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle23Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle47Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedITEM_7Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedUPLOADWidget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle41Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedUNITNAMEWidget4.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedITEM_4Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax9widget/generated/GeneratedRectangle45Widget.dart';

/* Frame iPhone 11 Pro Max - 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 918.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 918.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 225, 232, 235),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 455.0,
                              height: 83.0,
                              child: GeneratedFrame3Widget4(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 835.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 83.0,
                              child: GeneratedFrame4Widget5(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 361.0,
                              height: 31.0,
                              child: GeneratedRectangle20Widget4(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 612.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 37.0,
                              child: GeneratedRectangle23Widget2(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 665.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 72.0,
                              child: GeneratedRectangle50Widget(),
                            ),
                            Positioned(
                              left: 67.0,
                              top: 689.0,
                              right: null,
                              bottom: null,
                              width: 104.0,
                              height: 28.0,
                              child: GeneratedLOCATIONWidget5(),
                            ),
                            Positioned(
                              left: 106.0,
                              top: 768.0,
                              right: null,
                              bottom: null,
                              width: 175.0,
                              height: 58.0,
                              child: GeneratedRectangle24Widget2(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 136.0,
                              right: null,
                              bottom: null,
                              width: 74.0,
                              height: 58.0,
                              child: GeneratedITEM_1Widget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 181.0,
                              right: null,
                              bottom: null,
                              width: 107.0,
                              height: 58.0,
                              child: GeneratedITEM_2Widget(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 222.0,
                              right: null,
                              bottom: null,
                              width: 139.0,
                              height: 58.0,
                              child: GeneratedITEM_3Widget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 279.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 58.0,
                              child: GeneratedITEM_4Widget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 333.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 58.0,
                              child: GeneratedITEM_5Widget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 386.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 58.0,
                              child: GeneratedITEM_6Widget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 439.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 58.0,
                              child: GeneratedITEM_7Widget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 489.0,
                              right: null,
                              bottom: null,
                              width: 95.0,
                              height: 58.0,
                              child: GeneratedITEM_8Widget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 539.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 58.0,
                              child: GeneratedITEM_9Widget(),
                            ),
                            Positioned(
                              left: 148.0,
                              top: 786.0,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 28.0,
                              child: GeneratedUPLOADWidget1(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 616.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 28.0,
                              child: GeneratedPINCODEWidget2(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 154.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle32Widget(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 200.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle33Widget(),
                            ),
                            Positioned(
                              left: 221.99998474121094,
                              top: 297.9998779296875,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle34Widget(),
                            ),
                            Positioned(
                              left: 221.0,
                              top: 352.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle37Widget(),
                            ),
                            Positioned(
                              left: 222.0,
                              top: 408.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle38Widget(),
                            ),
                            Positioned(
                              left: 222.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle39Widget(),
                            ),
                            Positioned(
                              left: 222.0,
                              top: 510.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle40Widget(),
                            ),
                            Positioned(
                              left: 221.0,
                              top: 556.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle41Widget(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 241.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedRectangle36Widget(),
                            ),
                            Positioned(
                              left: 276.0,
                              top: 169.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle25Widget3(),
                            ),
                            Positioned(
                              left: 276.0,
                              top: 214.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle42Widget(),
                            ),
                            Positioned(
                              left: 276.0,
                              top: 256.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle43Widget(),
                            ),
                            Positioned(
                              left: 276.0,
                              top: 313.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle44Widget(),
                            ),
                            Positioned(
                              left: 276.0,
                              top: 367.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle45Widget(),
                            ),
                            Positioned(
                              left: 276.0,
                              top: 423.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle46Widget(),
                            ),
                            Positioned(
                              left: 276.0,
                              top: 469.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle47Widget(),
                            ),
                            Positioned(
                              left: 276.0,
                              top: 525.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle48Widget(),
                            ),
                            Positioned(
                              left: 276.0,
                              top: 571.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 15.0,
                              child: GeneratedRectangle49Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 107.0,
                              right: null,
                              bottom: null,
                              width: 139.0,
                              height: 31.0,
                              child: GeneratedUNITNAMEWidget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
