import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget2/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget2/generated/GeneratedRegisterasWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget2/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget2/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget2/generated/GeneratedCLIENTWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget2/generated/GeneratedCOMPANYWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatedloadingscreenwidget2/generated/GeneratedKUDUMBASREEWidget.dart';

/* Frame Loading screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoadingscreenWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 40, 39, 118),
                ),
              ),
              Positioned(
                left: 78.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 42.0,
                child: GeneratedRegisterasWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 64.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 428.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 64.0,
                child: GeneratedRectangle7Widget1(),
              ),
              Positioned(
                left: 139.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 45.0,
                child: GeneratedCOMPANYWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 64.0,
                child: GeneratedRectangle8Widget1(),
              ),
              Positioned(
                left: 159.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 45.0,
                child: GeneratedCLIENTWidget(),
              ),
              Positioned(
                left: 105.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 45.0,
                child: GeneratedKUDUMBASREEWidget(),
              )
            ]),
      ),
    ));
  }
}
