import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax6widget/generated/GeneratedRectangle22Widget3.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax6widget/generated/GeneratedCOMPANYNAMEWidget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax6widget/generated/GeneratedFrame4Widget8.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax6widget/generated/GeneratedRectangle24Widget5.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax6widget/generated/GeneratedCONTACTWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax6widget/generated/GeneratedRectangle23Widget4.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax6widget/generated/GeneratedIDWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax6widget/generated/GeneratedRectangle20Widget6.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax6widget/generated/GeneratedFrame3Widget7.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax6widget/generated/GeneratedDETAILSWidget.dart';

/* Frame iPhone 11 Pro Max - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 918.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 918.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 225, 232, 235),
                              ),
                            ),
                            Positioned(
                              left: 6.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 455.0,
                              height: 83.0,
                              child: GeneratedFrame3Widget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 835.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 83.0,
                              child: GeneratedFrame4Widget8(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 361.0,
                              height: 39.0,
                              child: GeneratedRectangle20Widget6(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 227.0,
                              right: null,
                              bottom: null,
                              width: 287.0,
                              height: 66.0,
                              child: GeneratedRectangle22Widget3(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 331.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 312.0,
                              child: GeneratedRectangle23Widget4(),
                            ),
                            Positioned(
                              left: 104.0,
                              top: 681.0,
                              right: null,
                              bottom: null,
                              width: 175.0,
                              height: 58.0,
                              child: GeneratedRectangle24Widget5(),
                            ),
                            Positioned(
                              left: 56.0,
                              top: 240.0,
                              right: null,
                              bottom: null,
                              width: 156.0,
                              height: 58.0,
                              child: GeneratedIDWidget(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 366.0,
                              right: null,
                              bottom: null,
                              width: 86.0,
                              height: 28.0,
                              child: GeneratedDETAILSWidget(),
                            ),
                            Positioned(
                              left: 142.0,
                              top: 699.0,
                              right: null,
                              bottom: null,
                              width: 97.0,
                              height: 28.0,
                              child: GeneratedCONTACTWidget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 155.0,
                              right: null,
                              bottom: null,
                              width: 201.0,
                              height: 31.0,
                              child: GeneratedCOMPANYNAMEWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
