import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax14widget/generated/GeneratedVectorWidget10.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax14widget/generated/GeneratedRectangle23Widget5.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax14widget/generated/GeneratedRectangle25Widget6.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax14widget/generated/GeneratedFromWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax14widget/generated/GeneratedFrame4Widget9.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax14widget/generated/GeneratedVectorWidget9.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax14widget/generated/GeneratedToWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax14widget/generated/GeneratedComposeemailWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax14widget/generated/GeneratedCOMPOSEWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax14widget/generated/GeneratedFrame3Widget8.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax14widget/generated/GeneratedVectorWidget11.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax14widget/generated/GeneratedRectangle20Widget7.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax14widget/generated/GeneratedSubjectWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax14widget/generated/GeneratedRectangle26Widget2.dart';

/* Frame iPhone 11 Pro Max - 14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax14Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 918.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 918.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 225, 232, 235),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 455.0,
                              height: 83.0,
                              child: GeneratedFrame3Widget8(),
                            ),
                            Positioned(
                              left: 339.704345703125,
                              top: 96.0,
                              right: null,
                              bottom: null,
                              width: 24.9973201751709,
                              height: 25.005022048950195,
                              child: GeneratedVectorWidget9(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 102.0,
                              right: null,
                              bottom: null,
                              width: 127.0,
                              height: 34.0,
                              child: GeneratedCOMPOSEWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 835.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 83.0,
                              child: GeneratedFrame4Widget9(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 361.0,
                              height: 39.0,
                              child: GeneratedRectangle20Widget7(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 211.0,
                              right: null,
                              bottom: null,
                              width: 361.0,
                              height: 39.0,
                              child: GeneratedRectangle25Widget6(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 288.0,
                              right: null,
                              bottom: null,
                              width: 371.0,
                              height: 88.0,
                              child: GeneratedRectangle23Widget5(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 396.0,
                              right: null,
                              bottom: null,
                              width: 371.0,
                              height: 408.0,
                              child: GeneratedRectangle26Widget2(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 142.0,
                              right: null,
                              bottom: null,
                              width: 156.0,
                              height: 58.0,
                              child: GeneratedFromWidget(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 299.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 25.0,
                              child: GeneratedSubjectWidget(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 414.0,
                              right: null,
                              bottom: null,
                              width: 149.0,
                              height: 25.0,
                              child: GeneratedComposeemailWidget(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 21.87744140625,
                              height: 21.3232421875,
                              child: GeneratedVectorWidget10(),
                            ),
                            Positioned(
                              left: 270.0127258300781,
                              top: 96.02054595947266,
                              right: null,
                              bottom: null,
                              width: 21.87500762939453,
                              height: 25.000036239624023,
                              child: GeneratedVectorWidget11(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 216.0,
                              right: null,
                              bottom: null,
                              width: 40.0,
                              height: 34.0,
                              child: GeneratedToWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
