import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedKGWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedPLACEWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedNOOFITEMSWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedPINCODEWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedVectorWidget7.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedUPLOADWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedMATERIALQUANTITYWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedLOCATIONWidget3.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedPLACEWidget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedRectangle25Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedORWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedFrame4Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax4widget/generated/GeneratedRectangle23Widget.dart';

/* Frame iPhone 11 Pro Max - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedFrame4Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(20.0),
        child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: Container(
                height: 938.0,
                child: Stack(children: [
                  Container(
                      width: constraints.maxWidth,
                      child: Container(
                        width: 414.0,
                        height: 938.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(20.0),
                        ),
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.circular(20.0),
                                child: Container(
                                  color: Color.fromARGB(255, 225, 232, 235),
                                ),
                              ),
                              Positioned(
                                left: -5.0,
                                top: 0.0,
                                right: null,
                                bottom: null,
                                width: 414.0,
                                height: 83.0,
                                child: GeneratedFrame3Widget(),
                              ),
                              Positioned(
                                left: 14.0,
                                top: 137.0,
                                right: null,
                                bottom: null,
                                width: 266.0,
                                height: 31.0,
                                child: GeneratedMATERIALQUANTITYWidget(),
                              ),
                              Positioned(
                                left: 168.0,
                                top: 311.0,
                                right: null,
                                bottom: null,
                                width: 166.0,
                                height: 31.0,
                                child: GeneratedNOOFITEMSWidget(),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 855.0,
                                right: null,
                                bottom: null,
                                width: 414.0,
                                height: 83.0,
                                child: GeneratedFrame4Widget1(),
                              ),
                              Positioned(
                                left: 30.0,
                                top: 192.0,
                                right: null,
                                bottom: null,
                                width: 116.0,
                                height: 58.0,
                                child: GeneratedRectangle20Widget(),
                              ),
                              Positioned(
                                left: 52.0,
                                top: 484.0,
                                right: null,
                                bottom: null,
                                width: 299.0,
                                height: 58.0,
                                child: GeneratedRectangle22Widget(),
                              ),
                              Positioned(
                                left: 57.0,
                                top: 617.0,
                                right: null,
                                bottom: null,
                                width: 299.0,
                                height: 58.0,
                                child: GeneratedRectangle23Widget(),
                              ),
                              Positioned(
                                left: 119.0,
                                top: 711.0,
                                right: null,
                                bottom: null,
                                width: 175.0,
                                height: 58.0,
                                child: GeneratedRectangle24Widget(),
                              ),
                              Positioned(
                                left: 27.0,
                                top: 296.0,
                                right: null,
                                bottom: null,
                                width: 116.0,
                                height: 58.0,
                                child: GeneratedRectangle21Widget(),
                              ),
                              Positioned(
                                left: 27.0,
                                top: 296.0,
                                right: null,
                                bottom: null,
                                width: 116.0,
                                height: 58.0,
                                child: GeneratedRectangle25Widget2(),
                              ),
                              Positioned(
                                left: 168.0,
                                top: 207.0,
                                right: null,
                                bottom: null,
                                width: 39.0,
                                height: 34.0,
                                child: GeneratedKGWidget(),
                              ),
                              Positioned(
                                left: 68.0,
                                top: 259.0,
                                right: null,
                                bottom: null,
                                width: 41.0,
                                height: 34.0,
                                child: GeneratedORWidget(),
                              ),
                              Positioned(
                                left: 68.0,
                                top: 380.0,
                                right: null,
                                bottom: null,
                                width: 127.0,
                                height: 34.0,
                                child: GeneratedLOCATIONWidget3(),
                              ),
                              Positioned(
                                left: 34.0,
                                top: 415.0,
                                right: null,
                                bottom: null,
                                width: 74.0,
                                height: 58.0,
                                child: GeneratedPLACEWidget(),
                              ),
                              Positioned(
                                left: 34.0,
                                top: 415.0,
                                right: null,
                                bottom: null,
                                width: 74.0,
                                height: 58.0,
                                child: GeneratedPLACEWidget1(),
                              ),
                              Positioned(
                                left: 167.0,
                                top: 729.0,
                                right: null,
                                bottom: null,
                                width: 85.0,
                                height: 28.0,
                                child: GeneratedUPLOADWidget(),
                              ),
                              Positioned(
                                left: 34.0,
                                top: 578.0,
                                right: null,
                                bottom: null,
                                width: 93.0,
                                height: 28.0,
                                child: GeneratedPINCODEWidget(),
                              ),
                              Positioned(
                                left: 27.0,
                                top: 389.4374694824219,
                                right: null,
                                bottom: null,
                                width: 29.65605926513672,
                                height: 28.49371337890625,
                                child: GeneratedVectorWidget7(),
                              )
                            ]),
                      ))
                ])),
          );
        }),
      ),
    ));
  }
}
