import 'package:flutter/material.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax7widget/generated/GeneratedUNITNAMEWidget5.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax7widget/generated/GeneratedRectangle26Widget1.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax7widget/generated/GeneratedOKWidget3.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax7widget/generated/GeneratedBUYITEMWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax7widget/generated/GeneratedRectangle22Widget2.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax7widget/generated/GeneratedSELLITEMWidget.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax7widget/generated/GeneratedRectangle24Widget4.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax7widget/generated/GeneratedFrame3Widget6.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax7widget/generated/GeneratedRectangle20Widget5.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax7widget/generated/GeneratedRectangle25Widget5.dart';
import 'package:flutterapp/salvadores_verdesapp/generatediphone11promax7widget/generated/GeneratedFrame4Widget7.dart';

/* Frame iPhone 11 Pro Max - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 918.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 409.0,
                      height: 905.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 225, 232, 235),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 455.0,
                              height: 83.0,
                              child: GeneratedFrame3Widget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 835.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 83.0,
                              child: GeneratedFrame4Widget7(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 361.0,
                              height: 39.0,
                              child: GeneratedRectangle20Widget5(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 254.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 100.0,
                              child: GeneratedRectangle22Widget2(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 409.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 100.0,
                              child: GeneratedRectangle25Widget5(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 409.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 100.0,
                              child: GeneratedRectangle26Widget1(),
                            ),
                            Positioned(
                              left: 127.0,
                              top: 445.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 31.0,
                              child: GeneratedBUYITEMWidget(),
                            ),
                            Positioned(
                              left: 104.0,
                              top: 565.0,
                              right: null,
                              bottom: null,
                              width: 175.0,
                              height: 58.0,
                              child: GeneratedRectangle24Widget4(),
                            ),
                            Positioned(
                              left: 172.0,
                              top: 583.0,
                              right: null,
                              bottom: null,
                              width: 34.0,
                              height: 28.0,
                              child: GeneratedOKWidget3(),
                            ),
                            Positioned(
                              left: 121.0,
                              top: 290.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 31.0,
                              child: GeneratedSELLITEMWidget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 155.0,
                              right: null,
                              bottom: null,
                              width: 139.0,
                              height: 31.0,
                              child: GeneratedUNITNAMEWidget5(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
